# Generated by Django 6.0.1 on 2026-02-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='currentquant',
            new_name='Current_Quantity',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='mouthsize',
            new_name='Mouth_Size',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='sku',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='supplier',
            new_name='supplied_by',
        ),
    ]
