# Generated by Django 6.0.1 on 2026-02-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_rename_createdat_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Current_Quantity',
            new_name='current_quantity',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Mouth_Size',
            new_name='mouth_size',
        ),
    ]
